module.exports = {
  testEnvironment: 'node',
  verbose: true,
  transform: { '^.+\\.ts$': 'ts-jest' },
  testRegex: '\\.spec\\.ts$',
  moduleFileExtensions: ['ts', 'js', 'json'],
  roots: ['./'],
  moduleNameMapper: {
    '@root(.*)$': '<rootDir>/src/$1',
    '@services(.*)$': '<rootDir>/src/services$1',
    '@utils(.*)$': '<rootDir>/src/utils$1',
    '@routes(.*)$': '<rootDir>/src/routes$1',
    '@mocks(.*)$': '<rootDir>/src/mocks/$1',
  },
  modulePathIgnorePatterns: ['/node_modules/.*'],
  coverageDirectory: '<rootDir>/coverage',
  collectCoverageFrom: ['src/**/*.ts', '!src/scripts/**/*'],
  collectCoverage: true,
  reporters: ['default'],
  coverageReporters: ['lcov', 'html', 'json', 'text'],
  setupFiles: ['./jest.setup.js'],
  testTimeout: 10000,
  coverageThreshold: {
    global: {
      statements: 95,
      branches: 68,
      functions: 95,
      lines: 95,
    },
  },
};
